GPT_TEMPLATES={
	"OxfordPets": [
        "a photo of a {}, a type of pet.",
        "a snapshot of a {}, a pet animal.",
        "an image of a {}, a delightful pet.",
        "a picture of a {}, a common pet selection.",
        "a photo of a {}, a beloved pet.",
        "an image of a {}, a category of pet.",
        "a photo of a {}, an example of a cherished pet.",
        "a picture of a {}, a beloved pet variety.",
        "a shot of a {}, a favored pet.",
        "a portrayal of a {}, a typical pet.",
        "a depiction of a {}, a popular pet choice.",
        "a photo of a {}, a domesticated pet.",
        "a view of a {}, an adored pet.",
        "an image of a {}, a preferred pet species.",
        "a photo of a {}, a known pet breed.",
        "a representation of a {}, a household pet.",
        "a glimpse of a {}, a pet companion.",
        "a photo of a {}, a member of the pet family.",
        "a snapshot of a {}, an esteemed pet type.",
        "a still of a {}, a beloved pet species.",
        "a picture of a {}, a frequent pet choice.",
        "a photo of a {}, a treasured pet.",
        "an image of a {}, a classic pet.",
        "a look at a {}, a pet many adore.",
        "a sight of a {}, a commonly owned pet.",
        "an image of a {}, a sought-after pet.",
        "a pic of a {}, a loved pet variety.",
        "a photograph of a {}, a preferred pet.",
        "a portrait of a {}, a cherished animal companion.",
        "a capture of a {}, a darling pet.",
        "a photo of a {}, a home's favorite.",
        "an image of a {}, a pet of choice.",
        "a glimpse at a {}, a delightful pet to own.",
        "a snapshot of a {}, a pet many cherish.",
        "a still shot of a {}, a pet of preference.",
        "a picture of a {}, a popular animal companion.",
        "a photograph of a {}, a familiar pet.",
        "an image of a {}, a pet one might adore.",
        "a photo of a {}, a prized pet in homes.",
        "a pic of a {}, a favorite among many.",
        "a rendering of a {}, a pet everyone loves.",
        "a photo of a {}, a constant pet companion.",
        "an image of a {}, a common pet in households.",
        "a snapshot of a {}, a recognized pet species.",
        "a portrait of a {}, a pet to cherish.",
        "a depiction of a {}, a pet many seek.",
        "a photo of a {}, a pet to adore.",
        "an image of a {}, a notable pet selection.",
        "a picture of a {}, a top pet pick.",
        "a capture of a {}, a pet that is well-loved."
    ],

    "OxfordFlowers": [
        "an image of a {}, a cherished flower species.",
        "a photo of a {}, a recognized flower type.",
        "a representation of a {}, a garden flower.",
        "a glimpse of a {}, a floral beauty.",
        "a snapshot of a {}, a common flower variety.",
        "a view of a {}, a decorative flower kind.",
        "an illustration of a {}, a unique flower species.",
        "a visual of a {}, an ornamental flower.",
        "an artwork of a {}, a symbolic flower.",
        "a rendering of a {}, a botanical wonder.",
        "a display of a {}, a classic flower species.",
        "a depiction of a {}, a rare flower kind.",
        "a portrait of a {}, a flowering plant.",
        "a shot of a {}, a natural floral entity.",
        "an exposure of a {}, a cultivated flower species.",
        "a scene of a {}, a wild flower variety.",
        "a frame of a {}, a beloved flower.",
        "a showpiece of a {}, an iconic flower.",
        "a representation of a {}, a perennial flower type.",
        "a graphic of a {}, a seasonal flower.",
        "an imprint of a {}, a traditional flower species.",
        "an observation of a {}, an evergreen flower kind.",
        "a perspective of a {}, a fragrant flower.",
        "an exhibit of a {}, a tropical flower species.",
        "a vision of a {}, a flower of significance.",
        "a spectacle of a {}, a vibrant flower kind.",
        "an instance of a {}, a celebrated flower type.",
        "a presentation of a {}, a flower of the meadows.",
        "a tableau of a {}, a bloom of the gardens.",
        "a profile of a {}, an age-old flower species.",
        "a panorama of a {}, a field flower.",
        "an embodiment of a {}, a flower of lore.",
        "a peek at a {}, a timeless flower variety.",
        "a sight of a {}, a cultivated bloom.",
        "a viewfinder of a {}, an exotic flower.",
        "a portrayal of a {}, a flower of tales.",
        "a still of a {}, a perennial bloom.",
        "a showcase of a {}, a flower of the wild.",
        "a feature of a {}, a cultivated floral specimen.",
        "an aspect of a {}, a bloom of nature.",
        "a trace of a {}, a historical flower type.",
        "a vista of a {}, a flower from the tropics.",
        "a likeness of a {}, a native flower species.",
        "a semblance of a {}, a blossom from the gardens.",
        "a model of a {}, a flower of legends.",
        "a study of a {}, a bloom of artistry.",
        "a figure of a {}, a floral masterpiece.",
        "an image of a {}, a bloom in full splendor.",
        "a capture of a {}, a flower of inspiration.",
        "a print of a {}, a bloom of the ages."
    ],

    "FGVCAircraft" : [
        "a picture of a {}, a type of aircraft.",
        "a photo of a {}, a renowned aircraft model.",
        "an image of a {}, a classic aircraft.",
        "a portrayal of a {}, an iconic aircraft.",
        "a snapshot of a {}, a member of the aircraft family.",
        "a depiction of a {}, a modern aircraft.",
        "an illustration of a {}, an esteemed aircraft design.",
        "a view of a {}, an advanced aircraft.",
        "a shot of a {}, a popular aircraft variant.",
        "a display of a {}, a historic aircraft.",
        "a picture of a {}, a significant aircraft.",
        "a representation of a {}, a celebrated aircraft model.",
        "a photograph of a {}, a member of the aircraft lineage.",
        "an impression of a {}, a common type of aircraft.",
        "a glimpse of a {}, a representative aircraft.",
        "a capture of a {}, a typical aircraft.",
        "an exhibit of a {}, a crucial aircraft in history.",
        "a showcase of a {}, a favorite among aircraft enthusiasts.",
        "a portrayal of a {}, a staple in aircraft design.",
        "a scene of a {}, an aircraft known for its performance.",
        "an image of a {}, a distinguishing aircraft.",
        "a rendering of a {}, an innovative aircraft.",
        "a depiction of a {}, a classic in aircraft engineering.",
        "a snapshot of a {}, a game-changing aircraft.",
        "a shot of a {}, a unique aircraft design.",
        "a view of a {}, an aircraft with a rich legacy.",
        "an impression of a {}, a breakthrough in aircraft technology.",
        "a portrayal of a {}, an aircraft with significant impact.",
        "an image of a {}, a pioneer among aircrafts.",
        "a display of a {}, an aircraft with a distinct style.",
        "a picture of a {}, a flagship aircraft.",
        "a capture of a {}, an aircraft with noteworthy features.",
        "a shot of a {}, an aircraft known for its capabilities.",
        "a view of a {}, a beloved aircraft design.",
        "an illustration of a {}, an aircraft that stands out.",
        "a snapshot of a {}, an aircraft that's recognized globally.",
        "a representation of a {}, an aircraft often seen in the skies.",
        "a photo of a {}, an aircraft that has left its mark.",
        "a glimpse of a {}, a famous aircraft.",
        "a capture of a {}, an aircraft with a legacy.",
        "a picture of a {}, an aircraft that's a marvel of engineering.",
        "a depiction of a {}, an aircraft that's a testament to innovation.",
        "a scene of a {}, an aircraft with a storied past."
    ],

    "DescribableTextures": [
        "{} texture.",
        "rough {} texture.",
        "smooth {} texture.",
        "soft {} texture.",
        "hard {} texture.",
        "bumpy {} texture.",
        "slick {} texture.",
        "gritty {} texture.",
        "grainy {} texture.",
        "fuzzy {} texture.",
        "silky {} texture.",
        "velvety {} texture.",
        "slippery {} texture.",
        "sticky {} texture.",
        "crumbly {} texture.",
        "spongy {} texture.",
        "rubbery {} texture.",
        "woolly {} texture.",
        "prickly {} texture.",
        "hairy {} texture.",
        "glassy {} texture.",
        "metallic {} texture.",
        "plastic {} texture.",
        "wooden {} texture.",
        "leathery {} texture.",
        "feathery {} texture.",
        "scaly {} texture.",
        "fibrous {} texture.",
        "coarse {} texture.",
        "fine {} texture.",
        "moist {} texture.",
        "dry {} texture.",
        "elastic {} texture.",
        "brittle {} texture.",
        "resilient {} texture.",
        "mushy {} texture.",
        "crispy {} texture.",
        "creamy {} texture.",
        "flaky {} texture.",
        "gooey {} texture.",
        "jelly-like {} texture.",
        "watery {} texture.",
        "sticky {} texture.",
        "matted {} texture.",
        "knobby {} texture.",
        "ridged {} texture.",
        "wrinkled {} texture.",
        "smooth and silky {} texture.",
        "rough and bumpy {} texture.",
        "soft and fluffy {} texture.",
        "hard and gritty {} texture.",
        "slippery and wet {} texture.",
        "dry and crumbly {} texture.",
        "elastic and stretchy {} texture.",
        "brittle and hard {} texture.",
        "resilient and bouncy {} texture.",
        "mushy and soft {} texture.",
        "crispy and crunchy {} texture.",
        "creamy and smooth {} texture.",
        "flaky and crumbly {} texture.",
        "gooey and sticky {} texture.",
        "jelly-like and wobbly {} texture.",
        "watery and moist {} texture."
    ],

    "EuroSAT" : [
        "a centered satellite photo of {}.",
        "a satellite image focused on {}.",
        "a direct satellite capture of {}.",
        "an overhead satellite snapshot of {}.",
        "a clear satellite view of {}.",
        "a straightforward satellite photograph of {}.",
        "a satellite picture zoomed in on {}.",
        "a close-up satellite image of {}.",
        "an unobstructed satellite photo of {}.",
        "a satellite photo centered on {}.",
        "a pinpoint satellite capture of {}.",
        "a detailed satellite image of {}.",
        "a precise satellite photo of {}.",
        "an explicit satellite picture of {}.",
        "an exact satellite capture of {}.",
        "a satellite photo highlighting {}.",
        "a satellite image honing in on {}.",
        "a focused satellite picture of {}.",
        "a satellite photo zooming in on {}.",
        "an up-close satellite image of {}.",
        "a satellite view focusing on {}.",
        "a satellite picture centering on {}.",
        "a direct satellite view of {}.",
        "a satellite image zeroing in on {}.",
        "a satellite photo of {} from above.",
        "a top-down satellite image of {}.",
        "a satellite picture of {} from overhead.",
        "a bird's-eye satellite view of {}.",
        "a satellite image of {} from the top.",
        "a high-angle satellite photo of {}.",
        "an elevated satellite picture of {}.",
        "a satellite view of {} from up high.",
        "a satellite picture capturing {} from above.",
        "an overhead satellite photo of {}.",
        "a satellite image capturing {} from overhead.",
        "a top view satellite picture of {}.",
        "a satellite photo looking down on {}.",
        "an aerial satellite image of {}.",
        "a satellite view capturing {} from the sky.",
        "a sky-high satellite picture of {}.",
        "a satellite photo of {} from the heavens.",
        "a heavenly satellite image of {}.",
        "a satellite picture of {} from up above.",
        "an upper-level satellite photo of {}.",
        "a high-up satellite image of {}.",
        "a satellite view of {} from the clouds.",
        "a cloud-level satellite picture of {}.",
        "a satellite photo of {} from the stratosphere.",
        "a stratospheric satellite image of {}.",
        "a satellite picture of {} from the atmosphere.",
        "an atmospheric satellite photo of {}.",
        "a satellite view of {} from space.",
        "a space-level satellite picture of {}.",
        "a satellite photo of {} from the cosmos.",
        "a cosmic satellite image of {}.",
        "a satellite picture of {} from the universe.",
        "a universal satellite photo of {}.",
        "a satellite view of {} from the galaxy.",
        "a galactic satellite picture of {}.",
        "a satellite photo of {} from the solar system.",
        "a solar satellite image of {}.",
        "a satellite picture of {} from the Milky Way.",
        "a Milky Way satellite photo of {}.",
        "a satellite view of {} from the galaxy cluster.",
        "a galaxy cluster satellite picture of {}.",
        "a satellite photo of {} from the supercluster.",
        "a supercluster satellite image of {}.",
        "a satellite picture of {} from the universe cluster.",
        "a universe cluster satellite photo of {}.",
        "a satellite view of {} from the cosmos cluster.",
        "a cosmos cluster satellite picture of {}.",
        "a satellite photo of {} from the multiverse.",
        "a multiverse satellite image of {}.",
        "a satellite picture of {} from the omniverse.",
        "an omniverse satellite photo of {}."
    ],

    "StanfordCars": [
        "a photo of a {}.",
        "a bad photo of a {}.",
        "a photo of many {}s.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "a toy {} in a video game.",
        "a beautiful painting of a {}.",
        "a funny doodle of a {}.",
        "a cute drawing of a {}.",
        "a striking photo of a {}.",
        "a photo of a {} with its owner.",
        "a photo of a {} on the road.",
        "a photo of a {} in a showroom."
    ],

    "Food101": [
        "a photo of {}, a delicious dish.",
        "an image of a {}, a mouthwatering cuisine.",
        "a snapshot showcasing {}, a delectable food item.",
        "a picture of {}, a favorite culinary delight.",
        "a photo featuring {}, a savory dish.",
        "an image displaying {}, a delightful meal.",
        "a representation of {}, a beloved food choice.",
        "a glimpse of {}, a culinary masterpiece.",
        "a photo capturing {}, a popular food option.",
        "an image highlighting {}, a cherished cuisine.",
        "a snapshot of {}, a classic comfort food.",
        "a picture of {}, a culinary work of art.",
        "a photo of {}, a must-try food.",
        "an image of {}, a traditional food favorite.",
        "a representation of {}, a local culinary specialty.",
        "a glimpse of {}, a global food sensation.",
        "a photo of {}, a well-known food classic.",
        "an image featuring {}, a regional dish.",
        "a snapshot showcasing {}, a cultural culinary gem.",
        "a picture of {}, a flavorful food tradition.",
        "a photo of {}, a popular street food.",
        "an image of {}, an international food.",
        "a snapshot of {}, a beloved food.",
        "a picture featuring {}, a homemade culinary delight.",
        "a photo capturing {}, a gastronomic masterpiece.",
        "an image highlighting {}, a gourmet food experience.",
        "a representation of {}, an exotic food adventure.",
        "a glimpse of {}, a fusion cuisine delight.",
        "a photo of {}, a favorite dish from around the world.",
        "an image of {}, a mouthwatering food discovery.",
        "a snapshot of {}, a culinary journey highlight.",
        "a picture of {}, a delectable dining experience.",
        "a photo of {}, a food lover's dream.",
        "an image featuring {}, a culinary delight worth savoring.",
        "a representation of {}, a flavorful food tradition.",
        "a glimpse of {}, an iconic food creation.",
        "a photo of {}, a beloved dish with a twist.",
        "an image of {}, a culinary innovation.",
        "a snapshot of {}, an Instagram-worthy food trend.",
        "a picture of {}, a foodie's ultimate indulgence.",
        "a photo of {}, a culinary masterpiece with a story.",
        "an image of {}, a dish steeped in history and flavor.",
        "a snapshot of {}, a delightful food experience.",
        "a picture of {}, a food sensation worth trying."
    ],

    "SUN397": [
        "a photo of a {}.",
        "a bad photo of a {}.",
        "a photo of many {}s.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "a toy {} in a video game.",
        "a beautiful painting of a {}.",
        "a funny doodle of a {}.",
        "a cute drawing of a {}.",
        "a striking photo of a {}.",
        "a photo of a {} with its surroundings.",
        "a photo of a {} in the city.",
        "a photo of a {} in the countryside.",
        "a photo of a {} in the mountains.",
        "a photo of a {} in the forest.",
        "a photo of a {} at the beach.",
        "a photo of a {} with flowers.",
        "a photo of a {} without flowers."
    ],

    "Caltech101": [
        "a photo of a {}.",
        "a bad photo of a {}.",
        "a photo of many {}s.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "a toy {} in a video game.",
        "a beautiful painting of a {}.",
        "a funny doodle of a {}.",
        "a cute drawing of a {}.",
        "a striking photo of a {}.",
        "a photo of a {} in a museum.",
        "a photo of a {} in a gallery.",
        "a photo of a {} at an exhibition.",
        "a photo of a {} in a studio.",
        "a photo of a {} in a workshop."
    ],

    "UCF101": [
        "a photo of a person doing {}.",
        "an image of a person performing {}.",
        "a snapshot of a person engaged in {}.",
        "a picture of a person in the act of {}.",
        "a photo featuring a person executing {}.",
        "an image showcasing a person practicing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}.",
        "a photo capturing a person doing {}.",
        "an image highlighting a person engaged in {}.",
        "a snapshot of a person in the midst of {}.",
        "a picture of a person performing {}.",
        "a photo of a person demonstrating {}.",
        "an image of a person showcasing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}.",
        "a photo capturing a person doing {}.",
        "an image highlighting a person engaged in {}.",
        "a snapshot of a person in the process of {}.",
        "a picture of a person performing {}.",
        "a photo of a person demonstrating {}.",
        "an image of a person showcasing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}.",
        "a photo capturing a person doing {}.",
        "an image highlighting a person engaged in {}.",
        "a snapshot of a person immersed in {}.",
        "a picture of a person performing {}.",
        "a photo of a person demonstrating {}.",
        "an image of a person showcasing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}.",
        "a photo capturing a person doing {}.",
        "an image highlighting a person engaged in {}.",
        "a snapshot of a person engrossed in {}.",
        "a picture of a person performing {}.",
        "a photo of a person demonstrating {}.",
        "an image of a person showcasing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}.",
        "a photo capturing a person doing {}.",
        "an image highlighting a person engaged in {}.",
        "a snapshot of a person absorbed in {}.",
        "a picture of a person performing {}.",
        "a photo of a person demonstrating {}.",
        "an image of a person showcasing {}.",
        "a representation of a person involved in {}.",
        "a glimpse of a person participating in {}."
    ],

    "ImageNet" : [
	    "an illustration of a {}.",
        "an image of a {}.",
        "a portrait of a {}.",
        "a rendering of a {}.",
        "a depiction of a {}.",
        "an artwork of a {}.",
        "a piece of art representing a {}.",
        "a graphical representation of a {}.",
        "a digital art of a {}.",
        "an artistic rendering of a {}.",
        "a creative representation of a {}.",
        "a unique portrayal of a {}.",
        "a visual representation of a {}.",
        "a hand-drawn picture of a {}.",
        "a digitally created image of a {}.",
        "a sculpture representing a {}.",
        "an abstract representation of a {}.",
        "a masterpiece depicting a {}.",
        "a detailed illustration of a {}.",
        "a vibrant image of a {}.",
        "an expressive drawing of a {}.",
        "a picturesque view of a {}.",
        "an artistic depiction of a {}.",
        "a beautiful portrayal of a {}.",
        "a magnificent representation of a {}.",
        "an exquisite painting of a {}.",
        "a stunning image of a {}.",
        "an elaborate illustration of a {}.",
        "an impressive rendering of a {}.",
        "a captivating depiction of a {}.",
        "a marvelous artwork of a {}.",
        "an incredible piece of art representing a {}.",
        "a breathtaking graphical representation of a {}.",
        "a spectacular digital art of a {}.",
        "an awe-inspiring artistic rendering of a {}.",
        "a delightful creative representation of a {}.",
        "a charming portrayal of a {}.",
        "a fascinating visual representation of a {}.",
        "a lovely hand-drawn picture of a {}.",
        "a striking digitally created image of a {}.",
        "a lifelike sculpture representing a {}.",
        "an extraordinary abstract representation of a {}.",
        "a timeless masterpiece depicting a {}.",
        "a sophisticated detailed illustration of a {}.",
        "a vivacious vibrant image of a {}.",
        "a heartwarming expressive drawing of a {}.",
        "a picturesque view of a {} in nature.",
        "an enchanting artistic depiction of a {}.",
        "a graceful beautiful portrayal of a {}.",
        "a grand magnificent representation of a {}.",
        "a refined exquisite painting of a {}."
    ]
}

CUSTOM_IMAGENET_TEMPLATES =[
    "a photo of a {}.",
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
]