GPT_LLAMA_TEMPLATES = {
	'DescribableTextures':[
        "describe the distinctive appearance of {} texture.",
        "what unique characteristics define the {} texture?",
        "can you detail the distinguishing features of the {} texture?",
        "what makes the {} texture stand out in terms of appearance?",
        "highlight the exceptional aspects of the {} texture's appearance.",
        "discuss the notable visual qualities of the {} texture.",
        "illuminate the aspects that make the {} texture visually unique.",
        "what are the defining visual elements of the {} texture?",
        "unpack the distinctive visual characteristics of the {} texture.",
        "explore the particular visual features that characterize the {} texture.",
        "can you delineate the special attributes that mark the {} texture's appearance?"
    ],
    'EuroSAT':[
        "describe the distinctive appearance of a centered satellite photo of {}.",
        "outline the unique visual traits observed in a centered satellite photo of {}.",
        "characterize the salient features visible in a centered satellite image of {}.",
        "depict the standout qualities in the appearance of a centered satellite photograph of {}.",
        "elaborate on the distinguishing aspects captured in a centered satellite photo of {}.",
        "explain the specific visual details that define a centered satellite photo of {}.",
        "give a detailed description of the visual uniqueness in a centered satellite photo of {}.",
        "illustrate the peculiar visual elements present in a centered satellite snapshot of {}.",
        "detail the remarkable visual attributes of a centered satellite photo of {}.",
        "donvey the distinctive imagery seen in a centered satellite photo of {}.",
        "present the defining visual characteristics of a centered satellite photo of {}."
    ],
    'FGVCAircraft':[
        "describe the distinctive appearance of a {}, a type of aircraft.",
        "explain the unique visual characteristics of a {}, an aircraft variety.",
        "detail the singular look of a {}, a kind of flying machine.",
        "outline the notable features of a {}, a category of aircraft.",
        "give a description of the unique aesthetic of a {}, a form of aircraft.",
        "characterize the unusual design of a {}, a type of aviation craft.",
        "discuss the distinctive style of a {}, a class of airplane.",
        "provide an overview of the special appearance of a {}, a sort of aircraft.",
        "elaborate on the particular outer form of a {}, a version of an aircraft.",
        "illustrate the exclusive design elements of a {}, a type of aeroplane.",
        "convey the individual physical traits of a {}, a model of aircraft."
    ],
    'OxfordPets': [
        "describe the distinctive appearance of a {}, a type of pet.",
        "detail the unique look of a {}, a pet variety.",
        "characterize the notable features of a {}, a pet species.",
        "explain the singular traits of a {}, a pet breed.",
        "illustrate the remarkable characteristics of a {}, a domestic animal.",
        "portray the specific physical attributes of a {}, a companion animal.",
        "outline the exceptional markings of a {}, a household pet.",
        "depict the individual appearance of a {}, an animal companion.",
        "sketch the distinct visuals of a {}, a pet kind.",
        "convey the particular aesthetic of a {}, a pet classification.",
        "represent the unusual form of a {}, a type of domestic pet."
    ],
    'OxfordFlowers': [
        "describe the distinctive appearance of a {}, a type of flower.",
        "outline the unique look of a {}, a flower variety.",
        "detail the distinguishing features of a {}, a species of flower.",
        "characterize the notable traits of a {}, a kind of flower.",
        "explain the specific appearance of a {}, a category of flower.",
        "portray the singular characteristics of a {}, a flower class.",
        "depict the remarkable attributes of a {}, a form of flower.",
        "convey the exceptional aspect of a {}, a flower type.",
        "render the peculiar visuals of a {}, a segment of flora.",
        "illustrate the particular form of a {}, a flower sort.",
        "sketch the standout qualities of a {}, a family of flower."
    ],
    'Food101':  [
        "describe the distinctive appearance of {}, a type of food.",
        "depict the unique look of {}, a kind of food.",
        "outline the notable features of {}, a category of food.",
        "characterize the peculiar visual traits of {}, a variety of food.",
        "explain the singular aesthetic of {}, a food type.",
        "give details on the distinguishing characteristics of {}, an example of food.",
        "illustrate the remarkable facade of {}, a food classification.",
        "convey the striking attributes of {}, a form of food.",
        "detail the individuality in appearance of {}, a food group.",
        "sketch the specific visual elements of {}, a segment of food.",
        "relay the exceptional visual identity of {}, a food category."
   ],
   'UCF101': [
        "describe the distinctive appearance of a person doing {}.",
        "detail the unique look of someone engaged in {}.",
        "characterize the striking features of a person while {}.",
        "outline the notable characteristics of an individual during {}.",
        "sketch the defining traits of a person when they are {}.",
        "convey the singular style of someone in the act of {}.",
        "depict the exceptional features of a person amidst {}.",
        "illustrate the individual appearance of someone busy with {}.",
        "highlight the specific visual traits of a person who is {}.",
        "present the remarkable aspects of someone's appearance while {}.",
        "profile the visual uniqueness of an individual who is {}."
    ],
    'ImageNet': [
        "describe the distinctive appearance of a {}.",
        "explain what sets a {} apart in terms of looks.",
        "portray the unique look of a {}.",
        "characterize the singular visual traits of a {}.",
        "outline the notable features of a {}'s appearance.",
        "detail the individual look characteristics of a {}.",
        "give a rundown of what makes a {}'s appearance stand out.",
        "depict the distinguishing physical qualities of a {}.",
        "sketch the standout characteristics of a {}'s form.",
        "describe what's visually unique about a {}.",
        "capture the essence of a {}'s distinct appearance."
    ],
    'StanfordCars': [
        "describe the distinctive appearance of a {}.",
        "explain what sets a {} apart in terms of looks.",
        "portray the unique look of a {}.",
        "characterize the singular visual traits of a {}.",
        "outline the notable features of a {}'s appearance.",
        "detail the individual look characteristics of a {}.",
        "give a rundown of what makes a {}'s appearance stand out.",
        "depict the distinguishing physical qualities of a {}.",
        "sketch the standout characteristics of a {}'s form.",
        "describe what's visually unique about a {}.",
        "capture the essence of a {}'s distinct appearance."
    ],
    'SUN397': [
        "describe the distinctive appearance of a {}.",
        "explain what sets a {} apart in terms of looks.",
        "portray the unique look of a {}.",
        "characterize the singular visual traits of a {}.",
        "outline the notable features of a {}'s appearance.",
        "detail the individual look characteristics of a {}.",
        "give a rundown of what makes a {}'s appearance stand out.",
        "depict the distinguishing physical qualities of a {}.",
        "sketch the standout characteristics of a {}'s form.",
        "describe what's visually unique about a {}.",
        "capture the essence of a {}'s distinct appearance."
    ],
    'Caltech101': [
        "describe the distinctive appearance of a {}.",
        "explain what sets a {} apart in terms of looks.",
        "portray the unique look of a {}.",
        "characterize the singular visual traits of a {}.",
        "outline the notable features of a {}'s appearance.",
        "detail the individual look characteristics of a {}.",
        "give a rundown of what makes a {}'s appearance stand out.",
        "depict the distinguishing physical qualities of a {}.",
        "sketch the standout characteristics of a {}'s form.",
        "describe what's visually unique about a {}.",
        "capture the essence of a {}'s distinct appearance."
    ]
}